all : 1.pdf 2.pdf 3.pdf 4.pdf 5.pdf

5.pdf: 5.md
	pandoc 5.md -o 5.pdf

4.pdf: 4.md
	pandoc 4.md -o 4.pdf

3.pdf: 3.md
	pandoc 3.md -o 3.pdf

2.pdf: 2.md
	pandoc 2.md -o 2.pdf

1.pdf: 1.md
	pandoc 1.md -o 1.pdf
